### ISSUE TITLE
 Sprint 1 - UX_Social Networks (login)

### ISSUE THREAD

**Issue by LeZderich** [CPNV-ES/MGReader#4]
This story is dedicated to the integration of a view enabling future dialogue with social networks.

**Comment by ShansheGundishvili** [comment]
The login page is done

The main page layout for initialisation is done, it needs a research button and maybe instead of having it divided by countries have it all together and have a filter

The structure for the whole project is done, it's in Readme.

The booking page isn't done or started, as the mechanics behind it needs to be decided

**Comment by LeZderich** [comment]
Understand how jest works. --> not 100%
Understand what jest mock is --> not 100%

Write the login.test class --> Not finished but the first test works.
Check Login Status of a Person --> Done
Log a Person In --> Not begun
Log a Person Out --> Not begun

Write a controller --> Not finished but has the method for the first test.
